/// Flutter icons IconsMetro
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IconsMetro
///      fonts:
///       - asset: fonts/IconsMetro.ttf
///
/// 
/// * Linecons, Copyright (C) 2013 by Designmodo
///         Author:    Designmodo for Smashing Magazine
///         License:   CC BY ()
///         Homepage:  http://designmodo.com/linecons-free/
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
///
import 'package:flutter/widgets.dart';

class IconsMetro {
  IconsMetro._();

  static const _kFontFam = 'IconsMetro';

  static const IconData location = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData bus = const IconData(0xe84d, fontFamily: _kFontFam);
}
